config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'categories#index'
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  resources :users do
    resources :categories do
      resources :expenses
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user, class_name: 'User'
  has_many :joins, dependent: :destroy, foreign_key: 'categories_id', class_name: 'Join'
  has_many :expenses, through: :joins

  validates :name, :icon, presence: true, length: { maximum: 50 }

  def total_expenses(user)
    expenses.where(user_id: user.id).sum(:amount)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[show edit update destroy]

  # GET /categories or /categories.json
  def index
    if current_user
      @categories = current_user.categories
    else
      redirect_to new_user_session_path
    end
  end

  # GET /categories/1 or /categories/1.json
  def show; end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit; end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)
    @category.user = current_user

    respond_to do |format|
      if @category.save
        format.html { redirect_to user_categories_path(current_user) }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to category_url(@category) }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = Category.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def category_params
    params.require(:category).permit(:name, :icon)
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>" class="category d-flex justify-content-between align-items-center p-3 mb-2 text-dark rounded border border-dark w-100">
    <div>
        <%= image_tag category.icon, class: "category-icon", alt: category.name %>
    </div>
    <div class="d-flex flex-column justify-content-center align-items-center">
        <h3 class="category-name mb-0 p-0 text-uppercase fw-bold">
            ➡️<%= link_to category.name, user_category_expenses_path(current_user, category) %>
        </h3>
        <p class="p-0 m-0 text-muted fs-6">
            <%= category.created_at.strftime("%d %b %Y") %>
        </p>
    </div>
    <p class="mb-0 p-0 text-muted fs-6">
        Total: <%= category.total_expenses(current_user) %> <span class="text-warning">$</span>
    </p>
</div>

app/views/categories/_form.html.erb
<%= form_with(url: user_categories_path(current_user), model: @category, local: true, class: "w-100 d-flex flex-column align-items-center") do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul class="list-unstyled">
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="w-100">
    <%= form.label :name %>
    <%= form.text_field :name, class: "w-100" %>
  </div>

  <div class="row border border-dark rounded m-1 p-2 m-md-5 p-md-5">
    <h2 class="col-12 text-center text-dark">Choose an icon for your category</h2>
    <div class="col-4 col-md-3 d-flex justify-content-around">
      <%= image_tag image_path('airplane.png'), class: "icon" %>
      <%= form.radio_button :icon, "airplane.png" %>
    </div>
    <div class="col-4 col-md-3 d-flex justify-content-around mb-3">
      <%= image_tag image_path('beach.png'), class: "icon" %>
      <%= form.radio_button :icon, "beach.png" %>
    </div>
    <div class="col-4 col-md-3 d-flex justify-content-around mb-3">
      <%= image_tag image_path('first-aid-kit.png'), class: "icon" %>
      <%= form.radio_button :icon, "first-aid-kit.png" %>
    </div>
    <div class="col-4 col-md-3 d-flex justify-content-around mb-3">
      <%= image_tag image_path('food.png'), class: "icon" %>
      <%= form.radio_button :icon, "food.png" %>
    </div>
    <div class="col-4 col-md-3 d-flex justify-content-around mb-3">
      <%= image_tag image_path('gift.png'), class: "icon" %>
      <%= form.radio_button :icon, "gift.png" %>
    </div>
    <div class="col-4 col-md-3 d-flex justify-content-around mb-3">
      <%= image_tag image_path('home.png'), class: "icon" %>
      <%= form.radio_button :icon, "home.png" %>
    </div>
    <div class="col-4 col-md-3 d-flex justify-content-around mb-3">
      <%= image_tag image_path('insurance.png'), class: "icon" %>
      <%= form.radio_button :icon, "insurance.png" %>
    </div>
    <div class="col-4 col-md-3 d-flex justify-content-around mb-3">
      <%= image_tag image_path('newlyweds.png'), class: "icon" %>
      <%= form.radio_button :icon, "newlyweds.png" %>
    </div>
    <div class="col-4 col-md-3 d-flex justify-content-around mb-3">
      <%= image_tag image_path('parking.png'), class: "icon" %>
      <%= form.radio_button :icon, "parking.png" %>
    </div>
    <div class="col-4 col-md-3 d-flex justify-content-around mb-3">
      <%= image_tag image_path('workplace.png'), class: "icon" %>
      <%= form.radio_button :icon, "workplace.png" %>
    </div>
    <div class="col-4 col-md-3 d-flex justify-content-around mb-3">
      <%= image_tag image_path('tic-tac-toe.png'), class: "icon" %>
      <%= form.radio_button :icon, "tic-tac-toe.png" %>
    </div>
    <div class="col-4 col-md-3 d-flex justify-content-around mb-3">
      <%= image_tag image_path('team-shirt.png'), class: "icon" %>
      <%= form.radio_button :icon, "team-shirt.png" %>
    </div>
    <div class="col-4 col-md-3 d-flex justify-content-around mb-3">
      <%= image_tag image_path('support.png'), class: "icon" %>
      <%= form.radio_button :icon, "support.png" %>
    </div>
    <div class="col-4 col-md-3 d-flex justify-content-around mb-3">
      <%= image_tag image_path('saving.png'), class: "icon" %>
      <%= form.radio_button :icon, "saving.png" %>
    </div>
    <div class="col-4 col-md-3 d-flex justify-content-around mb-3">
      <%= image_tag image_path('profits.png'), class: "icon" %>
      <%= form.radio_button :icon, "profits.png" %>
    </div>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Show this category", @category %> |
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/index.html.erb
<% if user_signed_in? %>
  <div class="page-header">
    <h2>Categories</h2>
  </div>
  <div id="categories" class="w-100 p-3 mb-2 text-dark m-3">
    <% if @categories.any? %>
      <ul>
        <p class="alert-info">Click on category name to see its expenses.</p>
        <% @categories.each do |category| %>
          <li class="d-flex justify-content-between align-items-center">
            <%= render category %>
          </li>
        <% end %>
      </ul>
    <% else %>
      <p class="alert-info text-center text-dark">You don't have any categories yet.</p>
    <% end %>
  </div>

  <%= link_to "New Category", new_user_category_path(current_user), class: "link-buttons mb-2" %>
<% else %>
  <div>
    <h3 class="alert-msg">You are not signed in</h3>
    <p class="alert-info">You need to Sign in to see your categories or Sign up if you don't have an account yet.</p>
    <p class="alert-info">Click on side menu to Sign in or Sign up.</p>
  </div>
<% end %>

app/views/categories/new.html.erb
<div class="page-header">
  <h2>New category</h2>
</div>

<div class="d-flex justify-content-around p-5 pb-2 w-100">
  <%= render "form", category: @category %>
  <div class="d-none d-md-block w-25"></div>
    <%= image_tag image_path('categories.png'), class: "d-none d-md-flex h-100" %>
  </div>
</div>

<div class="d-flex justify-content-around w-100 pb-3">
  <%= link_to "Back to categories", user_categories_path(current_user), class: "link-buttons" %>
</div>